import type { EffectForgeProject } from "@effectforge/schema";

export function createClickBurstStars(seed = 101): EffectForgeProject {
  const now = new Date().toISOString();
  return {
    format: "effectforge",
    formatVersion: 1,
    id: "proj_click_burst_stars",
    name: "Click Burst Stars",
    seed,
    canvas: {
      width: 1920,
      height: 1080,
      background: { type: "color", value: "#080810" },
      sizingMode: "fill-container",
      maxDpr: 2,
    },
    timeline: { duration: 6, loop: true, markers: [] },
    layers: [
      {
        id: "layer_ambient_stars",
        name: "Ambient Stars",
        kind: "particles",
        enabled: true,
        locked: false,
        opacity: 1,
        blendMode: "additive",
        emitter: {
          shape: { type: "box", size: { x: 3, y: 1.8, z: 0 } },
          space: "local",
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          scale: { x: 1, y: 1, z: 1 },
          rate: 25,
          bursts: [],
          startDelay: 0,
          duration: null,
          loop: true,
          prewarm: false,
          maxParticles: 3000,
        },
        lifetime: { kind: "random-range", min: 1.5, max: 3 },
        speed: { kind: "random-range", min: 0.05, max: 0.2 },
        size: { kind: "random-range", min: 0.008, max: 0.02 },
        color: { kind: "constant", value: "#aaccff" },
        initialOpacity: { kind: "random-range", min: 0.2, max: 0.6 },
        opacityOverLifetime: { type: "linear", start: 1, end: 0 },
        behaviors: [{ type: "drag", coefficient: 0.1 }],
        billboardMode: "camera-facing",
      },
      {
        id: "layer_click_bursts",
        name: "Click Bursts",
        kind: "particles",
        enabled: true,
        locked: false,
        opacity: 1,
        blendMode: "additive",
        emitter: {
          shape: { type: "point" },
          space: "local",
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          scale: { x: 1, y: 1, z: 1 },
          rate: 0,
          bursts: [],
          startDelay: 0,
          duration: null,
          loop: true,
          prewarm: false,
          maxParticles: 2000,
        },
        lifetime: { kind: "random-range", min: 0.4, max: 0.9 },
        speed: { kind: "random-range", min: 1, max: 2.5 },
        size: { kind: "random-range", min: 0.015, max: 0.035 },
        color: {
          kind: "gradient",
          gradient: {
            colorStops: [
              { position: 0, color: "#ffffff" },
              { position: 0.5, color: "#88ddff" },
              { position: 1, color: "#ff66cc" },
            ],
          },
        },
        initialOpacity: { kind: "constant", value: 1 },
        sizeOverLifetime: { type: "linear", start: 1, end: 0 },
        opacityOverLifetime: { type: "linear", start: 1, end: 0 },
        behaviors: [
          { type: "cursor-attract", strength: 0.5, radius: 0.2 },
          { type: "drag", coefficient: 0.35 },
        ],
        billboardMode: "camera-facing",
      },
    ],
    assets: {},
    exportPreferences: {
      portableSource: false,
      reducedMotionPolicy: "reduce-intensity",
    },
    metadata: { createdAt: now, updatedAt: now, tags: ["preset", "pointer", "click"] },
  };
}
