import type { EffectForgeProject } from "@effectforge/schema";
import type { ExportOptions, ExportedFile } from "./types.js";

export const DEFAULT_RUNTIME_VERSION = "0.1.0";

export function slugifyPackageName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "effectforge-effect";
}

export function resolveExportOptions(
  project: EffectForgeProject,
  options: ExportOptions = {},
): { packageName: string; runtimeVersion: string } {
  return {
    packageName: options.packageName ?? slugifyPackageName(project.name),
    runtimeVersion: options.runtimeVersion ?? DEFAULT_RUNTIME_VERSION,
  };
}

export function projectJsonFile(project: EffectForgeProject, path = "src/effect-project.json"): ExportedFile {
  return {
    path,
    content: `${JSON.stringify(project, null, 2)}\n`,
  };
}

export const THIRD_PARTY_NOTICES = `# Third-Party Notices

This exported project uses EffectForge runtime dependencies:

| Package | License | Purpose |
|---------|---------|---------|
| @effectforge/runtime | MIT | Effect playback runtime |
| three | MIT | WebGL rendering |

See https://github.com/mrdoob/three.js/blob/dev/LICENSE for Three.js license details.
`;

export const README_FOOTER = `
## Development

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

## Production build

\`\`\`bash
pnpm build
\`\`\`

Generated by EffectForge. The runtime has no editor dependencies.
`;
